API/urls.py
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from rest_framework import routers
from rest_framework.schemas import get_schema_view
from .views import CredentialViewSet, DeviceViewSet, ConnectionProtocolViewSet, TemplateViewSet, TemplateGroupViewSet, \
    DeviceTypeViewSet, InventoryViewSet

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
# router.register(r'user', UserViewSet)
router.register(r'credential', CredentialViewSet)
router.register(r'device', DeviceViewSet)
router.register(r'template', TemplateViewSet)
router.register(r'template_group', TemplateGroupViewSet)
router.register(r'connection_protocol', ConnectionProtocolViewSet)
router.register(r'inventory', InventoryViewSet)
router.register(r'device_type', DeviceTypeViewSet)


# app_name = 'API'
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('openapi', get_schema_view(
        title="CAPSNET - NetDevOps Tool",
        description="API Documentation",
        version="1.0.0"
    ), name='openapi-schema'),
    path('swagger-ui/', TemplateView.as_view(
        template_name='swagger-ui.html',
        extra_context={'schema_url': 'openapi-schema'}
    ), name='swagger-ui'),
]

CAPSNET/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard import views as dashboard_views

admin.site.site_header = "CAPSNET - Admin Portal"
admin.site.site_title = "CAPSNET - Admin Portal"
admin.site.index_title = "Admin Page"

urlpatterns = [
    path('admin/', admin.site.urls),

    #Auth
    path('signup/', dashboard_views.signupuser, name="signupuser"),
    path('logout/', dashboard_views.logoutuser, name="logoutuser"),
    path('login/', dashboard_views.loginuser, name="loginuser"),

    # API URLs
    path('api/', include('API.urls')),
    # Dashboard URLs
    path('', include('dashboard.urls')),
    # Devices URLs
    path('devices/', include('devices.urls')),
    # Templates URLs
    path('templates/', include('apptemplates.urls')),
    # Provisioning URLs
    path('provisioning/', include('provisioning.urls')),
    # Tools URLS
    path('tools/', include('tools.urls')),
    # Reports URLs
    path('reports/', include('reports.urls')),
    # Settings URLs
    path('settings/', include('appsettings.urls')),
]

devices/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views
from django.conf import settings

app_name = 'devices'

urlpatterns = [
    path('', views.all_devices, name="all_devices"),
    # Paths for the devices/device/ path
    path('device/<int:device_pk>/', views.device_details, name='device_details'),
    path('add/', views.add_device, name="add_device"),
    # Paths for the devices/discover/ path
    path('discover/', views.discover_devices, name="discover_devices"),
    path('discover/<int:seeddevice_pk>/', views.discover_details, name='discover_details'),
    path('discover/<int:seeddevice_pk>/edit', views.discover_details_edit, name='discover_details_edit'),
    # Paths for the devices/manage/ path
    path('manage/', views.manage_devices, name="manage_devices"),
]

tools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views
from django.conf import settings

app_name = 'tools'

urlpatterns = [
    path('', views.tools_home, name="tools_home"),
]

devices/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from appsettings.models import Credential

# Abstract base classes
class TrackedModel(models.Model):
    """
    Adds basic items change tracking
    """
    created = models.DateTimeField(editable=False, blank=True, null=True, help_text="When created")
    changed = models.DateTimeField(editable=False, blank=True, null=True, help_text="Last changed")

    def pre_save(self):
        if self.changed is None:  # first time new object only
            self.created = timezone.now()
        self.changed = timezone.now()  # update every save/update

    def save(self, *args, **kwargs):
        self.pre_save()
        super().save(*args, **kwargs)
        return self

    class Meta:
        abstract = True  # does not inherit

# Create your models here.


class DeviceType(models.Model):
    type_name = models.CharField(max_length=256, unique=True, blank=False, null=False, help_text="Device type (unique)")
    description = models.CharField(max_length=64, default="", blank=True, null=True, help_text="Short description")

    def __str__(self):
        out_str = str(self.type_name)
        if self.description not in ["", " ", None]:
            out_str += " (" + str(self.description) + ")"
        return out_str


class ConnectionProtocol(models.Model):
    protocol_name = models.CharField(max_length=256, unique=True, blank=False, null=False, help_text="Device type (unique)")
    protocol_port = models.IntegerField(default=0, blank=False, null=False, help_text="TCP/UDP port")
    description = models.CharField(max_length=64, default="", blank=True, null=True, help_text="Short description")

    def __str__(self):
        return str(self.protocol_name) + " (port: " + str(self.protocol_port) + ")"


class SeedDevice(TrackedModel):
    enable = models.BooleanField(default=True, help_text="Enable/disable seeding of this device")
    seed_host_or_ip = models.CharField(unique=True, default=None, max_length=100, help_text="Enter IP or hostname to seed device")
    discovered = models.DateTimeField(editable=False, blank=True, null=True, help_text="Date discovered")
    credential = models.ForeignKey(Credential, on_delete=models.PROTECT, blank=True, default=None, null=True,
                                            help_text="Choose authentication username")
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.seed_host_or_ip)


class DeviceGroups(TrackedModel):
    groupname = models.CharField(max_length=100, blank=False, help_text="Device group name")



class Device(TrackedModel):
    enable = models.BooleanField(default=True, help_text="Enable/Disable scanning of this device")
    groupname = models.ForeignKey(DeviceGroups, on_delete=models.PROTECT, null=True,
                                  blank=True, default=None, help_text="Device group")
    management_ip = models.GenericIPAddressField(unique=True, default=None, max_length=15, blank=False, null=False, help_text="Management IP")
    hostname = models.CharField(default=None, max_length=256, blank=True, null=True, help_text="Device HOSTNAME")
    vendor = models.CharField(max_length=100, blank=True, help_text="Device vendor name")
    model = models.CharField(max_length=100, blank=True, help_text="Device model name")
    software = models.CharField(max_length=100, blank=True, help_text="Device software version")
    device_type = models.CharField(max_length=100, blank=True, help_text="Device softare filename")
    connection_protocol = models.ForeignKey(ConnectionProtocol, on_delete=models.PROTECT, blank=True, default=None, help_text="Choose connection protocol/port")
    credential = models.ForeignKey(Credential, on_delete=models.PROTECT, blank=True, default=None,
                                            help_text="Choose authentication username")
    device_type = models.ForeignKey(DeviceType, blank=True, on_delete=models.PROTECT)
    notes = models.TextField(default=None, blank=True, null=True, help_text="Notes")

    def __str__(self):
        device_name = ""
        if self.hostname:
            device_name = self.hostname
            if self.management_ip:
                device_name += " (" + str(self.management_ip) + ")"
        elif self.management_ip:
            device_name = self.management_ip

        return device_name

    def common_name(self):
        return self.__str__()

    def save(self, *args, **kwargs):
        if self.changed is None:  # first time new object only
            self.created = timezone.now()
        self.changed = timezone.now()  # update every save/update
        super().save(*args, **kwargs)


class Inventory(models.Model):
    device = models.ForeignKey(Device, related_name="inventory_task", blank=False, null=False, on_delete=models.CASCADE,
                               help_text="Device")
    part_id = models.CharField(max_length=100, help_text="Part number", blank=True, null=True)
    type = models.CharField(max_length=100, help_text="Part type", blank=True, null=True)
    notes = models.CharField(max_length=100, default=None, blank=True, null=True, help_text="Notes")

    def __str__(self):
        device_name = ""
        if self.device.hostname:
            device_name = self.device.hostname
            if self.device.management_ip:
                device_name += " - " + str(self.device.management_ip)
        elif self.device.management_ip:
            device_name = self.device.management_ip

        return self.part_id + " (" + device_name + ")"

devices/forms.py
from django.forms import ModelForm
from .models import SeedDevice
from appsettings.models import Credential


class SeedDeviceForm(ModelForm):
    class Meta:
        model = SeedDevice
        fields = ['seed_host_or_ip', 'credential']

devices/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Device, SeedDevice
from appsettings.models import Credential
from ipaddress import ip_address, IPv4Address
from .forms import SeedDeviceForm
from django.contrib.auth.decorators import login_required

# Create your views here.\


@login_required()
def all_devices(request):
    devices = Device.objects.all()
    credentials = Credential.objects.all()
    page = 'devices'
    pagedetail = page + '.all_devices'
    context = {
        'devices': devices,
        'credentials': credentials,
        'page': page,
        'pagedetail': pagedetail
    }
    return render(request, "devices/all_devices.html", context)


@login_required()
def add_device(request):
    page = 'devices'
    pagedetail = page + '.add_device'
    context = {
        'form': SeedDeviceForm,
        'page': page,
        'pagedetail': pagedetail
    }
    if request.method == 'GET':
        return render(request, 'devices/add_device.html', context)
    else:
        # Create error based on validation of IP/hostname.
        error = ""
        # track for a valid return.  if valid, then save to database.
        valid_return = False


        # Get the list of devices so we can compare the IP to see if it already exists.
        devices = Device.objects.all()
        seeds = SeedDevice.objects.all()
        returned_seed = request.POST['seed_host_or_ip']

        if validIPAddress(returned_seed) == "IPv4":
            error = returned_seed + ' is a valid IPv4 address. Adding to discovery queue.'
            valid_return = True
        elif validIPAddress(returned_seed) == "Invalid":
            error = "Invalid IP Address entered. Enter a valid host or IP address to continue."
            protocol, ip_add, cidr = validCIDR(returned_seed)
            if protocol is not ["", " ", None]:
                valid_return = True
                error = returned_seed + ' is a valid CIDR format ' + protocol + ' address. Adding to discovery queue.'
        elif returned_seed is ["", " ", None]:
            error = "Host is blank. Enter a valid host or IP address to continue."
        elif returned_seed is not ["", " ", None]:
            error = "Host " + returned_seed + validIPAddress(returned_seed) +' is not in the database. Adding to discovery queue.'
            valid_return = True
        else:
            error = "Skipping hostname: " + validIPAddress(returned_seed)

        for device in devices:
            if device.management_ip == returned_seed:
                error = 'Duplicate management IP: ' + returned_seed + \
                        '.  This device has already been added.  Add a device that ' \
                        'isn''t in the database and try again.'
                valid_return = False
            if device.hostname == returned_seed:
                error = 'Duplicate hostname ' + returned_seed + \
                        '.  This device has already been added.  Add a device that ' \
                        'isn''t in the database and try again.'
                valid_return = False

        for seed in seeds:
            if seed.seed_host_or_ip == returned_seed:
                error = 'Duplicate added: ' + returned_seed + \
                        '.  This device/subnet has already been added.  Add a device or subnet that ' \
                        'isn''t in the database and try again.'
                valid_return = False


        # If we got IPv4, IPv6 or CIDR format return and no error
        if valid_return:
            # Get form from POST
            form = SeedDeviceForm(request.POST)
            # Put this in DB, but don't save.
            newform = form.save(commit=False)
            # Add user info to the form before saving.
            newform.user = request.user
            # Save the database if we received a valid input in the form.
            newform.save()
        # Return user to add_device page, with the form, and any errors(or successes)
        context['error'] = error
        return render(request, 'devices/add_device.html', context)


@login_required()
def discover_devices(request):
    if request.method == 'GET':
        seeds = SeedDevice.objects.all()
        page = 'devices'
        pagedetail = page + '.discover_devices'
        context = {
            'seeds': seeds,
            'page': page,
            'pagedetail': pagedetail
        }
        return render(request, "devices/discover_devices.html", context)



@login_required()
def discover_details(request, seeddevice_pk):
    if request.method == 'GET':
        # Show individual seed details
        seed = get_object_or_404(SeedDevice, pk=seeddevice_pk)
        credentials = Credential.objects.all()
        context = {
            'seed': seed,
            'credentials': credentials
        }
        return render(request, 'devices/discover_details.html', context)


@login_required()
def discover_details_edit(request, seeddevice_pk):
    if request.method == 'GET':
        # Show individual seed details
        seed = get_object_or_404(SeedDevice, pk=seeddevice_pk)
        credentials = Credential.objects.all()
        context = {
            'seed': seed,
            'credentials': credentials
        }
        return render(request, 'devices/discover_details_edit.html', context)


@login_required()
def manage_devices(request):
    page = 'devices'
    pagedetail = page + '.manage_devices'
    context = {
        'page': page,
        'pagedetail': pagedetail
    }
    return render(request, "devices/manage_devices.html", context)


@login_required()
def device_details(request, device_pk):
    # Show individual device details
    device = get_object_or_404(Device, pk=device_pk)

    page = 'devices'
    pagedetail = page + '.all_devices'
    context = {
        'device': device,
        'page': page,
        'pagedetail': pagedetail
    }

    if request.method == 'GET':
        return render(request, 'devices/device_details.html', context)


def validIPAddress(IP: str) -> str:
    try:
        return "IPv4" if type(ip_address(IP)) is IPv4Address else "IPv6"
    except ValueError:
        return "Invalid"


def validCIDR(IP : str) -> str:
    valid_return = False
    output = {}

    # Replace backslash with forward slash
    value = IP.replace("\\", "/")

    if "/" in value:
        # Split string into CIDR and IP
        split = value.split("/")
        output['ip_address'] = split[0]
        output['cidr'] = split[1]
        # Check if first of string has IPv4 address
        if validIPAddress(output['ip_address']) == "IPv4":
            # Check if back of string has d digit less than or equal to 32
            if int(output['cidr']) <= 32:
                valid_return = True
                output['protocol'] = "IPv4"
        # Check if first of string has IPv4 address
        elif validIPAddress(output['ip_address']) == "IPv6":
            # Check if back of string has d digit less than or equal to 32
            if int(output['cidr']) <= 128:
                valid_return = True
                output['protocol'] = "IPv6"

    if valid_return:
        return output
    else:
        return False

devices/templates/devices/add_device.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block stylesets %}

  <!-- Custom styles for this page -->
  <link href="{% static 'dashboard/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}Device Details - {{ device.common_name }}{% endblock %}

{% block content %}




    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">

        <!-- Card Body -->
        <div class="card-body">

            <div class="col-8 col-xl-10">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Add new Device</h5>
                        <h6 class="card-subtitle text-muted">Add device to seed for discovery.</h6>
                    </div>
                    <div class="card-body">

                        <h5>{{ error }}</h5>
                        <form method = "POST" id="add_device">
                            <div class="form-group row">
                            {% csrf_token %}
                            {{ form.as_p }}
                            </div>
                            <div class="form-group row">
                            <b>*Leave credential blank to scan all credentials.</b>
                            </div>


                            <div class="form-group row">
                                <div class="col-sm-10 ml-sm-auto">

                                    <button type="submit" class="btn btn-primary btn-icon-split">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-check"></i>
                                        </span>
                                        <span class="text">Add Device</span>
                                    </button>
                                     <a href="{% url 'devices:all_devices' %}" class="btn btn-success btn-icon-split">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-backward"></i>
                                        </span>
                                        <span class="text">Cancel</span>
                                    </a>

                                </div>

                            </div>

                        </form>
                    </div>
                </div>
            </div>


        </div>

    </div>
            <a href="{% url 'devices:all_devices' %}"><i class="fa fa-backward"></i>&nbsp;Back to All Devices</a>




{% endblock %}

devices/templates/devices/all_devices.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block stylesets %}

  <!-- Custom styles for this page -->
  <link href="{% static 'dashboard/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

    {% block title %}Devices home{% endblock %}

{% block content %}
    <h3>Devices home</h3>
  <!-- DataTales Example -->
  <div class="card shadow mb-4">

    <!-- Dropdown right -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">All devices</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Device Actions:</div>
            <a class="dropdown-item" href="{% url 'devices:add_device' %}">Add Device</a>
            <a class="dropdown-item" href="{% url 'devices:discover_devices' %}">Discover Devices</a>
            <a class="dropdown-item" href="{% url 'devices:manage_devices' %}">Manage Devices</a>
            <div class="dropdown-divider"></div>
            <div class="dropdown-header">Tools:</div>
            <a class="dropdown-item" href="{% url 'tools:tools_home' %}">Run tool</a>
            <a class="dropdown-item" href="{% url 'tools:tools_home' %}">Schedule jobs</a>
        </div>
      </div>
    </div>

        <!-- Start card body -->
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Management IP</th>
                      <th>Hostname</th>
                      <th>Vendor</th>
                      <th>Model</th>
                      <th>Software</th>
                      <th>Connection Protocol</th>
                      <th>Device Type</th>
                        <th>Serial Number</th>
                    </tr>
                  </thead>
                  <tbody>
                      {% for device in devices %}
                        <tr>
                            <td><a href="{% url 'devices:device_details' device.id %}">{{ device.management_ip }}</a></td>
                            <td><a href="{% url 'devices:device_details' device.id %}">{{ device.hostname }}</a></td>
                            <td>{{ device.vendor }}</td>
                            <td>{{ device.model }}</td>
                            <td>{{ device.software }}</td>
                            <td>{{ device.connection_protocol }}</td>
                            <td>{{ device.device_type }}</td>
                            <td>{{ device.device_type }}</td>
                        </tr>
                      {% endfor %}
                  </tbody>
                </table>

              </div>
            </div>
          </div>
        <!-- end card body -->


{% endblock %}

{% block scripts %}

    <!-- Page level plugins -->
  <script src="{% static 'dashboard/vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'dashboard/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'dashboard/js/demo/datatables-demo.js' %}"></script>

{% endblock %}

devices/templates/devices/discover_details.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block stylesets %}

  <!-- Custom styles for this page -->
  <link href="{% static '/dashboard/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}Discover Device - Details{% endblock %}

{% block content %}

    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Seeded Device Details</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
            <div class="dropdown-header">Tools:</div>
            <a class="dropdown-item" href="{% url 'devices:discover_details_edit' seed.id %}">Edit seed</a>
            <a class="dropdown-item" href="#">Delete seed</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        <table cellpadding=5>
            <tr>
                <td>ID</td>
                <td><b>{{ seed.id }}</b></td>
            </tr>
            <tr>
                <td>Seed Address</td>
                <td><b>{{ seed.seed_host_or_ip }}</b></td>
            </tr>
            <tr>
                <td>Enabled</td>
                <td><b>{{ seed.enable }}</b></td>
            </tr>
            <tr>
                <td>Created Date</td>
                <td><b>{{ seed.created.date }}</b></td>
            </tr>
            <tr>
                <td>Discovered</td>
                <td><b>{{ seed.discovered.date }}</b></td>
            </tr>
            <tr>
                <td>Seeded Credential</td>
                <td><b>{{ seed.credential }}</b></td>
            </tr>
        </table>


    </div>

    </div>
    <a href="{% url 'devices:discover_devices' %}"><i class="fa fa-backward"></i>&nbsp;Back to Discover Devices</a>




{% endblock %}

devices/templates/devices/discover_devices.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block stylesets %}

  <!-- Custom styles for this page -->
  <link href="{% static 'dashboard/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

    {% block title %}Discover Devices{% endblock %}

{% block content %}
    <h3>Discover Devices</h3>
  <!-- DataTales Example -->
  <div class="card shadow mb-4">

    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Seeded device addresses</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Device Actions:</div>
            <a class="dropdown-item" href="{% url 'devices:add_device' %}">Add Device</a>
            <a class="dropdown-item" href="{% url 'devices:discover_devices' %}">Discover Devices</a>
            <a class="dropdown-item" href="{% url 'devices:manage_devices' %}">Manage Devices</a>
            <div class="dropdown-divider"></div>
            <div class="dropdown-header">Tools:</div>
            <a class="dropdown-item" href="{% url 'tools:tools_home' %}">Run tool</a>
            <a class="dropdown-item" href="{% url 'tools:tools_home' %}">Schedule jobs</a>
        </div>
      </div>
    </div>

        <!-- Start card body -->
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                        <th>Seed address</th>
                        <th>Seeded Credentials</th>
                        <th>Enabled</th>
                        <th>Added Date/Time</th>
                        <th>Discovered Date/Time</th>
                        <th>Ping Reply</th>
                        <th>SSH/Telnet Response</th>
                        <th>SNMP Credential</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                      {% for seed in seeds %}
                        <tr>
                            <td><a href="{% url 'devices:discover_details' seed.id %}">{{ seed.seed_host_or_ip }}</a></td>
                            <td>{{ seed.credential }}</td>
                            <td>{{ seed.enable }}</td>
                            <td>{{ seed.created.date }}</td>
                            <td>{{ seed.discovered.date }}</td>
                            <td>TODO</td>
                            <td>TODO</td>
                            <td>TODO</td>
                            <td>TODO</td>
                            <td>

                              <!-- Action dropdown -->
                              <div class="dropdown no-arrow">
                                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                                      <div class="dropdown-header">Device Actions:</div>
                                        <a class="dropdown-item" href="{% url 'devices:discover_details_edit' seed.id %}">Edit seed</a>
                                        <a class="dropdown-item" href="{% url 'devices:discover_details' seed.id %}">Seed Details</a>
                                        <a class="dropdown-item" href="{% url 'devices:discover_devices' %}">Discover Devices</a>
                                        <a class="dropdown-item" href="{% url 'devices:manage_devices' %}">Manage Devices</a>
                                        <div class="dropdown-divider"></div>
                                        <div class="dropdown-header">Tools:</div>
                                        <a class="dropdown-item" href="{% url 'tools:tools_home' %}">Run tool</a>
                                        <a class="dropdown-item" href="{% url 'tools:tools_home' %}">Schedule jobs</a>
                                    </div>
                                  </div>

                            </td>
                        </tr>

                      {% endfor %}
                  </tbody>
                </table>

              </div>
            </div>
          </div>
        <!-- end card body -->


{% endblock %}

{% block scripts %}

    <!-- Page level plugins -->
  <script src="{% static 'dashboard/vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'dashboard/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'dashboard/js/demo/datatables-demo.js' %}"></script>

{% endblock %}

devices/templates/devices/manage_devices.html
{% extends 'dashboard/base.html' %}

{% block content %}
Manage Devices placeholder
{% endblock %}

devices/templates/devices/old_details.html
{% extends "dashboard/base.html" %}

{% block title %}Device Details - {{ device.seed_host_or_ip }}{% endblock %}

{% block content %}
    <h3>{{ device.seed_host_or_ip }}</h3>
    {{ device.hostname }}<br>
    {{ device.vendor }}<br>
    {{ device.model }}<br>
    {{ device.software }}<br>
    {{ device.device_type }}

{% endblock %}