API/urls.py
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from rest_framework import routers
from rest_framework.schemas import get_schema_view
from .views import CredentialViewSet, DeviceViewSet, ConnectionProtocolViewSet, TemplateViewSet, TemplateGroupViewSet, \
    DeviceTypeViewSet, InventoryViewSet

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
# router.register(r'user', UserViewSet)
router.register(r'credential', CredentialViewSet)
router.register(r'device', DeviceViewSet)
router.register(r'template', TemplateViewSet)
router.register(r'template_group', TemplateGroupViewSet)
router.register(r'connection_protocol', ConnectionProtocolViewSet)
router.register(r'inventory', InventoryViewSet)
router.register(r'device_type', DeviceTypeViewSet)


# app_name = 'API'
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('openapi', get_schema_view(
        title="CAPSNET - NetDevOps Tool",
        description="API Documentation",
        version="1.0.0"
    ), name='openapi-schema'),
    path('swagger-ui/', TemplateView.as_view(
        template_name='swagger-ui.html',
        extra_context={'schema_url': 'openapi-schema'}
    ), name='swagger-ui'),
]

CAPSNET/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard import views as dashboard_views

admin.site.site_header = "CAPSNET - Admin Portal"
admin.site.site_title = "CAPSNET - Admin Portal"
admin.site.index_title = "Admin Page"

urlpatterns = [
    path('admin/', admin.site.urls),

    #Auth
    path('signup/', dashboard_views.signupuser, name="signupuser"),
    path('logout/', dashboard_views.logoutuser, name="logoutuser"),
    path('login/', dashboard_views.loginuser, name="loginuser"),

    # API URLs
    path('api/', include('API.urls')),
    # Dashboard URLs
    path('', include('dashboard.urls')),
    # Devices URLs
    path('devices/', include('devices.urls')),
    # Templates URLs
    path('templates/', include('apptemplates.urls')),
    # Provisioning URLs
    path('provisioning/', include('provisioning.urls')),
    # Tools URLS
    path('tools/', include('tools.urls')),
    # Reports URLs
    path('reports/', include('reports.urls')),
    # Settings URLs
    path('settings/', include('appsettings.urls')),
]

dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views
from django.conf import settings

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('ui-alerts/', views.uialerts, name="uialerts"),
]

devices/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views
from django.conf import settings

app_name = 'devices'

urlpatterns = [
    path('', views.all_devices, name="all_devices"),
    # Paths for the devices/device/ path
    path('device/<int:device_pk>/', views.device_details, name='device_details'),
    path('add/', views.add_device, name="add_device"),
    # Paths for the devices/discover/ path
    path('discover/', views.discover_devices, name="discover_devices"),
    path('discover/<int:seeddevice_pk>/', views.discover_details, name='discover_details'),
    path('discover/<int:seeddevice_pk>/edit', views.discover_details_edit, name='discover_details_edit'),
    # Paths for the devices/manage/ path
    path('manage/', views.manage_devices, name="manage_devices"),
]

reports/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views
from django.conf import settings

app_name = 'reports'

urlpatterns = [
    path('', views.reports_home, name="reports_home"),
]

templates/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views
from django.conf import settings

app_name = 'templates'

urlpatterns = [
    path('', views.templates_home, name="templates_home"),
]

tools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views
from django.conf import settings

app_name = 'tools'

urlpatterns = [
    path('', views.tools_home, name="tools_home"),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate

# Create your views here.


def signupuser(request):
    # Create user in built in authentication module
    if request.method == 'GET':
        return render(request, 'dashboard/signupuser.html', {'form': UserCreationForm()})
    else:
        # Create a new device if POST type
        if request.POST['password1'] == request.POST['password2']:
            try:
                # Take variables from post and create new user object with them.
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                # Save the object into the database.
                user.save()
                # Login the user
                login(request, user)
                # Return the user to the dashboard
                return redirect('dashboard:dashboard')
            # If IntegrityError exist, display error on signup page
            except IntegrityError:
                return render(
                    request, 'dashboard/signupuser.html',
                    {'form': UserCreationForm(),
                     'error': 'That username is already taken. Try again.'}
                )
        else:
            # If passwords don't match, display error on signup page
            return render(
                request, 'dashboard/signupuser.html',
                {'form': UserCreationForm(),
                 'error': 'Passwords did not match.  Try again.'}
            )


def dashboard(request):
    return render(request, "dashboard/dashboard.html")


def uialerts(request):
    return render(request, "dashboard/ui-alerts.html")


def logoutuser(request):
    if request.method == "POST":
        logout(request)
        return redirect('dashboard:dashboard')


def loginuser(request):
    # Create user in built in authentication module
    if request.method == 'GET':
        return render(request, 'dashboard/login.html')
    else:
        user = authenticate(request, username=request.POST['username1'], password=request.POST['password1'])
        if user is None:
            return render(request, 'dashboard/login.html', {'error': 'Username and password do not match.'})
        else:

            # Login the user
            login(request, user)
            return redirect('dashboard:dashboard')

dashboard/templates/dashboard/admin.html
{% extends "dashboard/base.html" %}

<!-- Add page specific stylesheets -->
{% block stylesets %}

{% endblock %}

<!-- Add page specific title -->
{% block title %}
    CAPSNET - Admin home
{% endblock %}

<!-- Add main content -->
{% block content %}
Admin home
    <br>
    <a href="{% url 'dashboard:admin' %}">Django Admin</a>"

{% endblock %}

<!-- Add page specific custom scripts -->
{% block scripts %}

{% endblock %}

dashboard/templates/dashboard/base_old.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "portfolio/Logo.png" %}">

    <title>{% block title %}{% endblock %}</title>
</head>

<body>







  <nav id="topNav" class="navbar fixed=top navbar-expand-lg navbar-dark bg-dark">
      <table class="navbar-brand">
            <tr>
                <th rowspan="2">
                    <a class="navbar-brand" href="{% url 'dashboard:dashboard' %}">
                      <img src="{% static "dashboard/Logo.png" %}" width="50" height="50" class="d-inline-block align-top" alt="Logo">
                    </a>
                </th>
                <th>
                    CAPSNET
                </th>
            </tr>
            <tr>
                <td>
                    <h5>Configuration Automation and Provisioning System for Networks</h5>
                </td>
            </tr>
      </table>

      <div class="collapse navbar-collapse text-right" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Signup</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Login</a>
        </ul>
      </div>
  </nav>
  <div class="sidenav">

    <ul>
        <li>
            <a href="{%   url 'dashboard:dashboard' %}">Dashboard</a>
        </li>
        <li>
            <a href="{%   url 'devices:all_devices' %}">Devices</a>
        </li>
        <li>
            <a href="{%   url 'templates:templates_home' %}">Templates</a>
        </li>
        <li>
            <a href="{%   url 'provisioning:provisioning_home' %}">Provisioning</a>
        </li>
        <li>
            <a href="{%   url 'tools:tools_home' %}">Tools</a>
        </li>
        <li>
            <a href="{%   url 'reports:reports_home' %}">Reports</a>
        </li>
        <li>
            <a href="{%   url 'settings:settings_home' %}">Settings</a>
        </li>
        <li>
            <a href="{%   url 'admin:index' %}">Admin</a>
        </li>
    </ul>
  </div>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

dashboard/templates/dashboard/dashboard.html
{% extends "dashboard/base.html" %}

    {% block title %}Dashboard home{% endblock %}

{% block content %}
Dashboard home

{% endblock %}

dashboard/templates/dashboard/login.html
{% extends "dashboard/base.html" %}

{% block title %}Login
{% endblock %}

{% block content %}


      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back! Login below.</h1>
                      <h2>{{ error }}</h2>
                  </div>
                  <form class="user" method="POST">
                      {% csrf_token %}
                    <div class="form-group">
                      <input type="text" name="username1" class="form-control form-control-user" id="username" aria-describedby="emailHelp" placeholder="Enter username">
                    </div>
                    <div class="form-group">
                      <input type="password" name="password1" class="form-control form-control-user" id="password" placeholder="Password">
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Remember Me</label>
                      </div>
                    </div>
                      <div class="form-group row">
                            <div class="col-sm-10 ml-sm-auto">
                                <button type="submit" class="btn btn-primary">Login</button>
                            </div>

                        </div>
                    <hr>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="forgot-password.html">Forgot Password?</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="{% url 'signupuser' %}">Create an Account!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>


{% endblock %}

dashboard/templates/dashboard/signupuser.html
{% extends 'dashboard/base.html' %}

{% block title %}Signup
{% endblock %}

{% block content %}



    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">

    <!-- Card Body -->
    <div class="card-body">

        <div class="col-12 col-xl-16">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">New User</h5>
                    <h6 class="card-subtitle text-muted">Enter your information to create a new account.</h6>
                </div>
                <div class="card-body">
                    <h2>{{ error }}</h2>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Sign Up</button>
                    </form>
                </div>
            </div>
        </div>


    </div>

    </div>
            <a href="{% url 'devices:all_devices' %}">  Back to All Devices</a>




{% endblock %}

dashboard/templates/dashboard/ui-alerts.html
{% extends 'dashboard/base.html' %}

{% block title %}UIAlerts
{% endblock %}

{% block content %}
Test
{% endblock %}